#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "bad number of parameters";
    exit
fi

c=0;

while read line
do
    if(grep )
done




# while IFS=";" read -r var1 var2 var3
# do
#     echo "$var1 $var2 $var3";

# done