#!/bin/bash

functie()
{
    if [ "$#" -ne 1 ]; then
	echo "Argument number violation"
	exit
    fi
    chr=$1;
    count=0;
    while  read -r line;
    do
	if((echo "$line" | grep -E "^[A-Z][A-Za-z0-9 ,.!?]*[.!?]$" | grep -v ",si" | grep -E -c $chr)>0) 
	then
            ((count++))
	fi
    done
    echo "Nr de linii corecte e: $count"
}
functie $1